import Navbar from '@/Components/Navbar/Page'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // const navMenu= ["Home", "About", "Services", "Contact"]
  const navMenu=[{"name":"Dashboard", "link":"/"}, {"name":"Team", "link":"/team"}, {"name":"Project", "link":"/project"}, {"name":"Calender", "link":"/calender"}]
  return (
    <html lang="en">
      
      <body className={inter.className}>
      
      <Navbar navMenu={navMenu}/>
      <div>{children}</div>
      
      </body>
    </html>
  )
}
