import Navbar from '@/Components/Navbar/Page'
import './globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  // const navMenu= ["Home", "About", "Services", "Contact"]
  const navMenu=[{"name":"Dashboard", "link":"/"}, {"name":"Team", "link":"/team"}, {"name":"Project", "link":"/project"}, {"name":"Calender", "link":"/calender"}]
  return (
    <html lang="en">
      <Head>
        <title>My page title</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
       
      </Head>
      <body className={inter.className}>
      
      <Navbar navMenu={navMenu}/>
      <div>{children}</div>
      
      </body>
    </html>
  )
}
